version: "2"
services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
       MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    healthcheck:
       test: ["CMD", "mysqladmin" ,"ping", "-h", "db"]
       timeout: 25s
       retries: 3 
       
  app:
    build: ./app
    image: lironv/attendance:latest
    links:
      - db
    ports:
      - "5000:5000"
    depends_on:
      - db
